### first route
GET http://localhost:8080/first-route/first-method

### Register user
POST http://localhost:8080/users
Content-Type: application/json

{
  "username": "RudolfHiOk",
  "name": "Rodolfo HiOk",
  "password": "abc123"
}
