### first route
GET http://localhost:8080/first-route/first-method

### Register user
POST http://localhost:8080/users
Content-Type: application/json

{
  "username": "rudolfhiok",
  "name": "Rodolfo HiOk",
  "password": "abc123"
}

### Register task
POST http://localhost:8080/tasks
Authorization: Basic rudolfhiok:abc123
Content-Type: application/json

{
  "title": "Teste criar uma nova tarefa",
  "description": "Descrição de teste para criar uma nova tarefa",
  "priority": "Alta",
  "startAt": "2023-10-14T09:30:00",
  "endAt": "2023-10-14T11:45:00"
}

### List tasks
GET http://localhost:8080/tasks
Authorization: Basic rudolfhiok:abc123

### Update task
PUT http://localhost:8080/tasks/4c3f388d-c752-4d88-b19f-e7f24d33e55b
Authorization: Basic rudolfhiok:abc123
Content-Type: application/json

{
  "title": "Teste atualizar uma nova tarefa",
  "description": "Descrição de teste para atualizar uma tarefa",
  "priority": "Alta",
  "startAt": "2023-10-14T09:30:00",
  "endAt": "2023-10-14T11:45:00"
}

### Partial update task
PUT http://localhost:8080/tasks/4c3f388d-c752-4d88-b19f-e7f24d33e55b
Authorization: Basic rudolfhiok:abc123
Content-Type: application/json

{
  "description": "Descrição de teste para atualizar somente descrição e prioridade de uma tarefa",
  "priority": "Média"
}

### Register task with more than 50 char in title
POST http://localhost:8080/tasks
Authorization: Basic rudolfhiok:abc123
Content-Type: application/json

{
  "title": "Teste criar uma nova tarefa com mais de 50 caracteres 1234567890 abcdefghijklmnopqrstuvwxyz",
  "description": "Descrição de teste para criar uma nova tarefa",
  "priority": "Alta",
  "startAt": "2023-10-14T09:30:00",
  "endAt": "2023-10-14T11:45:00"
}

### Register other user
POST http://localhost:8080/users
Content-Type: application/json

{
  "username": "testuser",
  "name": "Test User",
  "password": "123456"
}

### Register task for other user
POST http://localhost:8080/tasks
Authorization: Basic testuser:123456
Content-Type: application/json

{
  "title": "Teste criar uma nova tarefa",
  "description": "Descrição de teste para criar uma nova tarefa",
  "priority": "Alta",
  "startAt": "2023-10-14T09:30:00",
  "endAt": "2023-10-14T11:45:00"
}

### List tasks for other user
GET http://localhost:8080/tasks
Authorization: Basic testuser:123456

### Deployed

### Register user
POST https://rocketseat-todolist.onrender.com/users
Content-Type: application/json

{
  "username": "rudolfhiok",
  "name": "Rodolfo HiOk",
  "password": "abc123"
}

### Register task
POST https://rocketseat-todolist.onrender.com/tasks
Authorization: Basic rudolfhiok:abc123
Content-Type: application/json

{
  "title": "Teste criar uma nova tarefa",
  "description": "Descrição de teste para criar uma nova tarefa",
  "priority": "Alta",
  "startAt": "2023-10-14T09:30:00",
  "endAt": "2023-10-14T11:45:00"
}

### List tasks
GET https://rocketseat-todolist.onrender.com/tasks
Authorization: Basic rudolfhiok:abc123

### Update task
PUT https://rocketseat-todolist.onrender.com/tasks/a3d44a3b-de3e-47a3-bcbb-a51fb86abaf7
Authorization: Basic rudolfhiok:abc123
Content-Type: application/json

{
  "title": "Teste atualizar uma nova tarefa",
  "description": "Descrição de teste para atualizar uma tarefa",
  "priority": "Alta",
  "startAt": "2023-10-14T09:30:00",
  "endAt": "2023-10-14T11:45:00"
}

### Partial update task
PUT https://rocketseat-todolist.onrender.com/tasks/a3d44a3b-de3e-47a3-bcbb-a51fb86abaf7
Authorization: Basic rudolfhiok:abc123
Content-Type: application/json

{
  "description": "Descrição de teste para atualizar somente descrição e prioridade de uma tarefa",
  "priority": "Média"
}